#!/usr/bin/env python3
"""
BigWigs Bar Color Override Generator

Generates bar color overrides for BigWigs SavedVariables based on the
canonical color system defined in BigWigs_Color_Guide.md.

Usage:
    python3 gen-bigwigs-colors.py                          # Print Lua snippet to stdout
    python3 gen-bigwigs-colors.py --merge <BigWigs.lua>    # Patch SavedVariables in-place
    python3 gen-bigwigs-colors.py --rollback <BigWigs.lua> # Restore most recent backup
    python3 gen-bigwigs-colors.py --rollback <BigWigs.lua> --from <bakfile>
"""

import argparse
import glob
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path

# Canonical palette from BigWigs_Color_Guide.md
# Each value is (R, G, B) as 0-255 integers
PALETTE = {
    "gray":   (0x6B, 0x72, 0x80),  # #6B7280 - Default / Info / Phase (dark)
    "red":    (0xFF, 0x33, 0x33),  # #FF3333 - Raid Damage (bright)
    "orange": (0xE6, 0x73, 0x00),  # #E67300 - Dodge / Move (medium-high)
    "yellow": (0xFF, 0xD7, 0x00),  # #FFD700 - Soak / Stack / Positioning (very bright)
    "green":  (0x22, 0xBB, 0x55),  # #22BB55 - Adds / Target Swap / Kicks (medium)
    "blue":   (0x44, 0x88, 0xFF),  # #4488FF - Knockback / Forced Movement (bright)
    "purple": (0xBB, 0x44, 0xEE),  # #BB44EE - Beams / Debuffs / Magic (medium)
    "brown":  (0x7A, 0x3B, 0x10),  # #7A3B10 - Tank Buster / Tank Swap (low)
}


def to_floats(r, g, b):
    """Convert 0-255 RGB to 0-1 floats matching BigWigs SavedVariables precision."""
    return (r / 255, g / 255, b / 255)


def format_rgb(r, g, b):
    """Format RGB floats as a Lua table value string."""
    fr, fg, fb = to_floats(r, g, b)
    return "{ %s, %s, %s }" % (
        f"{fr:.14g}", f"{fg:.14g}", f"{fb:.14g}"
    )


def parse_mapping(path):
    """Parse bigwigs_colors.lua mapping file.

    Returns dict: { "BigWigs_Bosses_Name": { spell_id: "category", ... }, ... }
    """
    mapping = {}
    current_boss = None

    with open(path) as f:
        for line in f:
            stripped = line.split("--")[0].strip()

            # Match boss table start: ["BigWigs_Bosses_Name"] = {
            m = re.match(r'\["(.+?)"\]\s*=\s*\{', stripped)
            if m:
                current_boss = m.group(1)
                mapping[current_boss] = {}
                continue

            # Match spell entry: [spellID] = "category",
            m = re.match(r'\[(-?\d+)\]\s*=\s*"(\w+)"', stripped)
            if m and current_boss:
                spell_id = int(m.group(1))
                category = m.group(2)
                if category not in PALETTE:
                    print(f"Warning: unknown category '{category}' for spell {spell_id} in {current_boss}",
                          file=sys.stderr)
                mapping[current_boss][spell_id] = category
                continue

            # Match table end
            if stripped.startswith("},"):
                current_boss = None

    return mapping


def generate_color_table(mapping, table_name):
    """Generate a single Lua color table (barColor or barEmphasized).

    Returns list of strings (lines).
    """
    lines = []
    indent = "\t\t\t\t"

    lines.append(f'{indent}["{table_name}"] = {{')

    # Default bar color (gray)
    gr, gg, gb = PALETTE["gray"]
    lines.append(f'{indent}\t["BigWigs_Plugins_Colors"] = {{')
    lines.append(f'{indent}\t\t["default"] = {format_rgb(gr, gg, gb)},')
    lines.append(f'{indent}\t}},')

    # Per-boss, per-spell colors
    for boss_key in sorted(mapping.keys()):
        spells = mapping[boss_key]
        lines.append(f'{indent}\t["{boss_key}"] = {{')
        for spell_id in sorted(spells.keys()):
            category = spells[spell_id]
            r, g, b = PALETTE[category]
            lines.append(f'{indent}\t\t[{spell_id}] = {format_rgb(r, g, b)},')
        lines.append(f'{indent}\t}},')

    lines.append(f'{indent}}},')
    return lines


def generate_snippet(mapping):
    """Generate the full Lua snippet for barColor and barEmphasized."""
    lines = []
    lines.append("-- Generated by gen-bigwigs-colors.py on %s" % datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    lines.append("-- Paste into BigWigs3DB.namespaces[\"BigWigs_Plugins_Colors\"].profiles[\"Default\"]")
    lines.append("")
    lines.extend(generate_color_table(mapping, "barColor"))
    lines.append("")
    lines.extend(generate_color_table(mapping, "barEmphasized"))
    return "\n".join(lines)


def find_table_range(content, table_key):
    """Find the byte range of a top-level key's table value within a Lua table.

    Searches for ["table_key"] = { ... }, and returns (start, end) byte offsets
    covering the entire entry including the trailing comma.
    Returns None if not found.
    """
    # Find the key
    pattern = re.escape(f'["{table_key}"]') + r'\s*=\s*\{'
    match = re.search(pattern, content)
    if not match:
        return None

    start = match.start()
    # Find matching closing brace by counting nesting
    depth = 0
    i = match.end() - 1  # position of the opening {
    while i < len(content):
        if content[i] == '{':
            depth += 1
        elif content[i] == '}':
            depth -= 1
            if depth == 0:
                # Include trailing comma and optional whitespace
                end = i + 1
                if end < len(content) and content[end] == ',':
                    end += 1
                return (start, end)
        i += 1

    return None


def generate_inline_table(mapping, table_name, indent_level):
    """Generate a color table formatted for inline insertion into SavedVariables."""
    indent = "\t" * indent_level
    lines = []

    lines.append(f'{indent}["{table_name}"] = {{')

    # Default bar color (gray)
    gr, gg, gb = PALETTE["gray"]
    lines.append(f'{indent}\t["BigWigs_Plugins_Colors"] = {{')
    lines.append(f'{indent}\t\t["default"] = {format_rgb(gr, gg, gb)},')
    lines.append(f'{indent}\t}},')

    # Per-boss, per-spell colors
    for boss_key in sorted(mapping.keys()):
        spells = mapping[boss_key]
        lines.append(f'{indent}\t["{boss_key}"] = {{')
        for spell_id in sorted(spells.keys()):
            category = spells[spell_id]
            r, g, b = PALETTE[category]
            lines.append(f'{indent}\t\t[{spell_id}] = {format_rgb(r, g, b)},')
        lines.append(f'{indent}\t}},')

    lines.append(f'{indent}}},')
    return "\n".join(lines)


def merge_into_file(filepath, mapping):
    """Merge generated color tables into an existing BigWigs.lua SavedVariables file.

    Creates a timestamped backup before modifying.
    """
    filepath = Path(filepath)
    if not filepath.exists():
        print(f"Error: {filepath} does not exist", file=sys.stderr)
        return False

    content = filepath.read_text(encoding="utf-8")

    # Create backup
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = filepath.with_name(f"{filepath.name}.bak.{timestamp}")
    # Use raw file copy — shutil.copy/copy2 fail on WSL→NTFS (permission errors)
    backup_path.write_bytes(filepath.read_bytes())
    print(f"Backup: {backup_path}", file=sys.stderr)

    # Find the Default profile within BigWigs_Plugins_Colors
    # We need to locate ourselves within:
    #   ["BigWigs_Plugins_Colors"] = { ["profiles"] = { ["Default"] = { ... } } }
    #
    # Strategy: find the Colors namespace, then find Default profile within it,
    # then find/replace barColor and barEmphasized within that.

    # First, find the BigWigs_Plugins_Colors namespace
    colors_ns_pattern = r'\["BigWigs_Plugins_Colors"\]\s*=\s*\{'
    # There may be multiple — we want the one inside ["namespaces"]
    # Find the correct one by looking for it after ["namespaces"]
    ns_match = re.search(r'\["namespaces"\]\s*=\s*\{', content)
    if not ns_match:
        print("Error: could not find [\"namespaces\"] in file", file=sys.stderr)
        return False

    # Search for BigWigs_Plugins_Colors after namespaces
    colors_match = re.search(colors_ns_pattern, content[ns_match.start():])
    if not colors_match:
        print("Error: could not find BigWigs_Plugins_Colors namespace", file=sys.stderr)
        return False

    colors_start = ns_match.start() + colors_match.start()

    # Find the Default profile within this namespace
    # Look for ["Default"] = { after ["profiles"] = {
    profiles_match = re.search(r'\["profiles"\]\s*=\s*\{', content[colors_start:])
    if not profiles_match:
        print("Error: could not find [\"profiles\"] in BigWigs_Plugins_Colors", file=sys.stderr)
        return False

    profiles_start = colors_start + profiles_match.end()

    default_match = re.search(r'\["Default"\]\s*=\s*\{', content[profiles_start:])
    if not default_match:
        print("Error: could not find [\"Default\"] profile in BigWigs_Plugins_Colors", file=sys.stderr)
        return False

    default_start = profiles_start + default_match.end()

    # Find the end of the Default profile table
    depth = 1
    default_end = default_start
    while default_end < len(content) and depth > 0:
        if content[default_end] == '{':
            depth += 1
        elif content[default_end] == '}':
            depth -= 1
        default_end += 1

    default_content = content[default_start:default_end - 1]  # content inside Default = { ... }

    # Detect indent: BigWigs SavedVariables may be unindented (flat) or tabbed.
    # Look for a sibling key inside Default that we don't modify to detect the style.
    sibling_match = re.search(r'^(\t*)\["bar(?:Background|Text)', default_content, re.MULTILINE)
    if not sibling_match:
        sibling_match = re.search(r'^(\t*)\["(?!barColor|barEmphasized)', default_content, re.MULTILINE)
    indent_level = len(sibling_match.group(1)) if sibling_match else 0

    # Replace or insert barColor
    new_bar_color = generate_inline_table(mapping, "barColor", indent_level)
    bar_color_range = find_table_range(default_content, "barColor")
    if bar_color_range:
        default_content = (
            default_content[:bar_color_range[0]] +
            new_bar_color +
            default_content[bar_color_range[1]:]
        )
    else:
        # Insert at the beginning
        default_content = new_bar_color + "\n" + default_content

    # Replace or insert barEmphasized
    new_bar_emph = generate_inline_table(mapping, "barEmphasized", indent_level)
    bar_emph_range = find_table_range(default_content, "barEmphasized")
    if bar_emph_range:
        default_content = (
            default_content[:bar_emph_range[0]] +
            new_bar_emph +
            default_content[bar_emph_range[1]:]
        )
    else:
        # Insert after barColor
        bar_color_end = default_content.find(new_bar_color) + len(new_bar_color)
        default_content = (
            default_content[:bar_color_end] +
            "\n" + new_bar_emph +
            default_content[bar_color_end:]
        )

    # Reconstruct the file
    new_content = content[:default_start] + default_content + content[default_end - 1:]

    filepath.write_text(new_content, encoding="utf-8")

    # Count spells
    total_spells = sum(len(spells) for spells in mapping.values())
    print(f"Merged {total_spells} spell colors across {len(mapping)} bosses into {filepath}", file=sys.stderr)
    return True


def rollback(filepath, from_file=None):
    """Restore a BigWigs.lua from backup."""
    filepath = Path(filepath)

    if from_file:
        from_path = Path(from_file)
        if not from_path.exists():
            print(f"Error: backup file {from_path} does not exist", file=sys.stderr)
            return False
    else:
        # Find most recent backup
        pattern = str(filepath) + ".bak.*"
        backups = sorted(glob.glob(pattern))
        if not backups:
            print(f"Error: no backup files found matching {pattern}", file=sys.stderr)
            return False
        from_path = Path(backups[-1])

    filepath.write_bytes(from_path.read_bytes())
    print(f"Restored {filepath} from {from_path}", file=sys.stderr)
    return True


def main():
    parser = argparse.ArgumentParser(description="BigWigs bar color override generator")
    parser.add_argument("--merge", metavar="FILE",
                        help="Merge colors into existing BigWigs.lua SavedVariables file")
    parser.add_argument("--rollback", metavar="FILE",
                        help="Restore BigWigs.lua from most recent backup")
    parser.add_argument("--from", dest="from_file", metavar="BAKFILE",
                        help="Specific backup file to restore from (with --rollback)")
    parser.add_argument("--mapping", metavar="FILE", default=None,
                        help="Path to bigwigs_colors.lua (default: same dir as script)")
    args = parser.parse_args()

    # Handle rollback
    if args.rollback:
        success = rollback(args.rollback, args.from_file)
        sys.exit(0 if success else 1)

    # Find mapping file
    if args.mapping:
        mapping_path = args.mapping
    else:
        script_dir = Path(__file__).resolve().parent
        mapping_path = script_dir / "bigwigs_colors.lua"

    if not Path(mapping_path).exists():
        print(f"Error: mapping file not found: {mapping_path}", file=sys.stderr)
        sys.exit(1)

    mapping = parse_mapping(mapping_path)

    if not mapping:
        print("Error: no boss mappings found in mapping file", file=sys.stderr)
        sys.exit(1)

    total_spells = sum(len(spells) for spells in mapping.values())
    print(f"Loaded {total_spells} spell mappings across {len(mapping)} bosses", file=sys.stderr)

    # Merge or snippet mode
    if args.merge:
        success = merge_into_file(args.merge, mapping)
        sys.exit(0 if success else 1)
    else:
        print(generate_snippet(mapping))


if __name__ == "__main__":
    main()
